<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[User Logged in Successfully!]]>
    </line>
  </reporter-output>
  <suite started-at="2024-11-04T22:58:21 IST" name="Default suite" finished-at="2024-11-04T22:58:26 IST" duration-ms="5286">
    <groups>
    </groups>
    <test started-at="2024-11-04T22:58:21 IST" name="Default test" finished-at="2024-11-04T22:58:26 IST" duration-ms="5286">
      <class name="dataProvider.ToLearnDataProvider1">
        <test-method signature="login([Ljava.lang.String;)[pri:0, instance:dataProvider.ToLearnDataProvider1@481a996b]" started-at="2024-11-04T22:58:21 IST" name="login" data-provider="loginData" finished-at="2024-11-04T22:58:25 IST" duration-ms="4354" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@131ef10]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[UserFailed to Login expected [SkillRary Ecommerce] but found [SkillRary Courses]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: UserFailed to Login expected [SkillRary Ecommerce] but found [SkillRary Courses]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at dataProvider.ToLearnDataProvider1.login(ToLearnDataProvider1.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login([Ljava.lang.String;)[pri:0, instance:dataProvider.ToLearnDataProvider1@481a996b]" started-at="2024-11-04T22:58:21 IST" name="login" data-provider="loginData" finished-at="2024-11-04T22:58:26 IST" duration-ms="5237" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@23348b5d]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[User Logged in Successfully!]]>
            </line>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- dataProvider.ToLearnDataProvider1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
